name: Build project

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - run: git fetch --prune --unshallow

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0
        
    - name: Install dependencies
      run: dotnet restore src/
      
    - name: Build
      run: dotnet build src/ --configuration Release --no-restore
      
    - name: Package
      run: bash thunderstore/make_package.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Thunderstore Package
        path: thunderstore/Wristimate.zip